redis:
  address: 127.0.0.1:6379
  network: tcp
  password:
  maxIdle: 1000
  MaxActive: 2000
  Timeout: 200
database:
  type: mysql
  user: root
  password: root
  dbName: goseckill
  address: 127.0.0.1:3306
  maxIdle: 100
  maxOpen: 150